### ISSUE TITLE
Types do not match docs

### ISSUE THREAD

**Issue by igo** [belladoreai/llama3-tokenizer-js#4]
```
// types.d
encode(prompt: string, add_bos_token?: boolean, add_preceding_space?: boolean, log_performance?: boolean): number[];
// docs
llama3Tokenizer.encode("Hello world!", { bos: false, eos: false })
```
I dont know what is actually in JS because it's so huge... I guess you should split it. I don't see any reasonable benefit of bundling code and data into a single file in a repo.

**Comment by belladoreai** [comment]
Thank you for reporting the issue with the types. I forgot to update them, as I don't use TypeScript myself. I will add a test for TypeScript specifically so that it will force me to update types in the future.

The benefit of baking data into the same file is that it simplifies the way that this library can be used in different environments. The main drawback of this approach is that data needs to be base64-encoded, which is inefficient for large data files. If we were to load the data from separate files, we could just load the data as binary files without any base64-encoding. However, if we had separate data files, we'd have to have separate data loading instructions for different environments, because you don't load files the same way in Node and browser (plus: more complexity to support CommonJS and TypeScript).

You mentioned that you couldn't open the JS file because it's so huge. Which program did you use to try to open it? For me it loads without a problem in Google Chrome and VSCode. I understand 3MB is so large that it will cause problems in some text editors (and even in VSCode with some configuration). Perhaps the baking-in-data made more sense back in Llama 1 when it was less than 700Kb.

Do you have any suggestion on what would be a way to keep data loading simple if we had separate binary data files? (or we can also consider base64-encoded .js data files if that helps keep things simpler)

**Comment by belladoreai** [comment]
I updated the types now and I tried to create a test for the types, but something is wrong with the TypeScript compilation. It seems to catch some errors in the types, but not all of them. For example, I accidentally had `llamaTokenizer` instead of `llama3Tokenizer` somewhere in the types file, and that's the kind of error that was caught by the test. But then the type of error that you reported, where the input parameters for the encode function didn't match code, that error was not caught by the test. TypeScript just compiled without issues even though the parameter types were clearly not matching. If you have time can you please take a look at what I could do to make TypeScript compile more strictly? The test inside `test/typescript-test`. I already have defined `"strict": true,` and `"skipLibCheck": false,`, I don't know what I'm missing here.

**Comment by igo** [comment]
Tests will not detect mistakes in dependency libs so you won't be able to check it from `test/typescript-test` project. If you want to check types then you might want to use `eslint` or similar directly inside the main project. 

You can use Rollup to create bundle instead of manually putting binary data into the code.

**Comment by belladoreai** [comment]
> Tests will not detect mistakes in dependency libs

But some mistakes _are_ detected in dependency libs when the `skipLibCheck` flag is set to false. As I mentioned, it caught one of the mistakes, but it didn't catch another one. Weird that it catches some mistakes but not all of them.

> If you want to check types then you might want to use eslint or similar directly inside the main project.

I tried this approach now, and it doesn't work either. It just supposedly lints a completely broken file without changing anything in the file and without logging any errors.

I don't think eslint is designed for this type of task. I think if I wanted to use eslint for this, it would require me to actually migrate my project into a TypeScript project before it would properly lint the `types.d.ts` file. Now that my project is a JavaScript project with simply a types file added to help TypeScript users import it, eslint doesn't seem to do anything with it.

I'm starting to think it's not worth the effort to try to automate the TypeScript type check.

> You can use Rollup to create bundle instead of manually putting binary data into the code

Hmmh, bundling the data does sound like a good tradeoff. It allows having a small source code file that can be opened with any text editor, and it avoids the problems with setting up different data loaders for different environments. I won't add any dependencies just to bundle the data, though (in this case it should be pretty simple to script).

**Comment by belladoreai** [comment]
I've now separated code and data into separate files and added a bundler script which creates the "single file with code and data baked in".
