### ISSUE TITLE
Provide a UMD module

### ISSUE THREAD

**Issue by Banbury** [belladoreai/llama3-tokenizer-js#5]
I'm trying to use llama3-tokenizer-js in a lowcode application (lowcoder-org/lowcoder), which only accepts Javascript libraries as UMD from a CDN. So any trickery with imports is not an option.
It would be nice, if you could provide a UMD version of the library. As far as I can see, all that would be needed is a different style of export.

**Comment by belladoreai** [comment]
I tried to add support for your use case now by adding this:

```
try { if (typeof module !== 'undefined' && module.exports) { exports.llama3Tokenizer = llama3Tokenizer } } catch (ex) { }
```

Try to load the file from Github CDN: https://belladoreai.github.io/llama3-tokenizer-js/bundle/llama3-tokenizer-with-baked-data.js

Does it work?

**Comment by Banbury** [comment]
I get the error message:
```
Unexpected token 'export'
```
I'm not sure, if this is an error of the app, but it really doesn't like the `export` statement.

**Comment by belladoreai** [comment]
The problem seems to be with mixing ES6 style export statements with CommonJS style export statements. I didn't find any clean solution to this problem. We can't make it conditional, because ES6 exports are not evaluated at runtime.

I changed the bundler script now such that it creates 2 separate files, one for ES6 and one for CommonJS.

Here is the CommonJS file: https://belladoreai.github.io/llama3-tokenizer-js/bundle/commonjs-llama3-tokenizer-with-baked-data.js

Does it work?
