### ISSUE TITLE
Consistently getting a discrepancy of 5 tokens between local and remote counts for Llama 3 8B Instruct Turbo model

### ISSUE THREAD

**Issue by TowhidKashem** [belladoreai/llama3-tokenizer-js#7]
Hi, I am making calls to `Meta-Llama-3-8B-Instruct-Turbo` on together ai's inference endpoint, they support the standard openAI api so my prompt chain looks something like:

`[{ message: '...', role: 'system' }, { message: '...', role: 'assistant' }, { message: '...', role: 'user' } and so on....]`

Anyway I used this tokenizer to measure the entire prompt's length and it gave me `1176`. To count the tokens I am adding both the role and the content of each message:

`this.tokenize(message.role).length + this.tokenize(message.content).length`

The together api response returns the actual token counts which is actually `1181` so it's only a **5** token discrepancy.

Moreover this is the discrepancy for all my requests consistently (no matter what the length of the messages array is), in other words there's always a 5 token count difference between what this tokenizer says and what the actual tokenizer from the api says. Which tells me that these unaccounted for tokens are probably used for some kind of initialization or metadata text.

Can anyone tell me what I am missing to get a more accurate count or is that not possible and I should just be happy with the 5 discrepancy?

First time counting my own tokens so I'm not sure how accurate these client side tokenizers are expected to be...
Thanks!

**Comment by belladoreai** [comment]
> First time counting my own tokens so I'm not sure how accurate these client side tokenizers are expected to be...

This client side tokenizer is supposed to give you the exact, accurate token count.

> Moreover this is the discrepancy for all my requests consistently (no matter what the length of the messages array is), in other words there's always a 5 token count difference between what this tokenizer says and what the actual tokenizer from the api says.

The discrepancy you are seeing is because of confusion around the special tokens. What you did when you called tokenize on `message.role` is that you tokenized the string "system". But special tokens actually look like this: "<|blabla|>" (not "blabla"). So you need to check what is the actual string that your library is shoving into the API (special tokens and your prompt and everything as a single string), and then you should tokenize that actual string.

**Comment by TowhidKashem** [comment]
> > First time counting my own tokens so I'm not sure how accurate these client side tokenizers are expected to be...
> 
> This client side tokenizer is supposed to give you the exact, accurate token count.
> 
> > Moreover this is the discrepancy for all my requests consistently (no matter what the length of the messages array is), in other words there's always a 5 token count difference between what this tokenizer says and what the actual tokenizer from the api says.
> 
> The discrepancy you are seeing is because of confusion around the special tokens. What you did when you called tokenize on `message.role` is that you tokenized the string "system". But special tokens actually look like this: "<|blabla|>" (not "blabla"). So you need to check what is the actual string that your library is shoving into the API (special tokens and your prompt and everything as a single string), and then you should tokenize that actual string.

Gotcha that makes sense! I'm just not sure how to use them with your lib though, tried a bunch of variations like:

```
llama3Tokenizer.encode('<|begin_of_text|>hello world<|end_of_text|>', { 
  bos: true,
  eos: true
}).length;

llama3Tokenizer.encode('<|begin_of_text|>hello world<|end_of_text|>').length;

llama3Tokenizer.encode('hello world<|eot_id|>').length;

// etc...
```

But it doesn't seem to be the right way. This is the model I'm using btw:

https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct

**Comment by belladoreai** [comment]
```
llama3Tokenizer.encode('<|begin_of_text|>hello world<|end_of_text|>', { 
  bos: true,
  eos: true
}).length;
```

When the `bos` parameter is set to `true`, a `<|begin_of_text|>` token is added. So when you tokenize `<|begin_of_text|>hello world` with `bos` true, you end up with the bos token TWICE: `<|begin_of_text|><|begin_of_text|>hello world`. Same thing with `eos` token.

```
llama3Tokenizer.encode('<|begin_of_text|>hello world<|end_of_text|>')
```

Here again the `bos` and `eos` parameters are true (by default), so you again end up with duplicate special tokens.

```
llama3Tokenizer.encode('hello world<|eot_id|>')
```

Because of the default parameter values, this tokenizes into `<|begin_of_text|>hello world<|eot_id|><|end_of_text|>`.

If you are tokenizing a string like `<|begin_of_text|>testing`, you don't want to add another bos token, so you should set `bos` to `false`.

Try this:

```
llama3Tokenizer.encode('<|begin_of_text|>hello world<|end_of_text|>', { 
  bos: false,
  eos: false
}).length;
```

**Comment by TowhidKashem** [comment]
> encode

ah that was it, I just had to set:

  bos: false,
  eos: false
  
  and then this function worked:
  
```
    getTokenCountForMessage({ role, content }: Message): number {
    let instruct = '<|begin_of_text|>';
    switch (role) {
      case 'system':
        instruct += `<|start_header_id|>system<|end_header_id|> ${content}<|eot_id|>`;
        break;
      case 'user':
        instruct += `<|start_header_id|>user<|end_header_id|> ${content}<|eot_id|>`;
        break;
      case 'assistant':
        instruct += `<|start_header_id|>assistant<|end_header_id|> ${content}<|eot_id|>`;
        break;
    }
    return this.getTokenCount(instruct);
  }
```

thanks for the help!
