### ISSUE TITLE
Update to llama3.1 tokenizer

### ISSUE THREAD

**Issue by AmgadHasan** [belladoreai/llama3-tokenizer-js#8]

**Comment by belladoreai** [comment]
I don't have time to look into this right now. I would appreciate it if anybody would investigate the differences between Llama 3 tokenizer and Llama 3.1 tokenizer (if any).

**Comment by HamadaFMahdi** [comment]
Based on the Meta Llama paper I believe it's the same tokenizer.

"All the results presented in this paper are for the Llama 3.1 models, which we will refer to as Llama 3 throughout for brevity."

"We use a vocabulary with 128K tokens. Our token vocabulary combines 100K tokens from the tiktoken tokenizer with 28K additional tokens to better support non-English languages. Compared to the Llama 2 tokenizer, our new tokenizer improves compression rates on a sample of English data from 3.17 to 3.94 characters per token. This enables the model to “read” more text for the same amount of training compute. We also found that adding 28K tokens from select non-English languages improved both compression ratios and downstream performance, with no impact on English tokenization."

They compare it to the Llama 2 tokenizer. If it were different they would have mentioned it in this section.

**Comment by belladoreai** [comment]
Thanks @HamadaFMahdi !

Let's leave this issue open for now.

**Comment by norlesh** [comment]
All the special and reserved token names for 3.0 and 3.1 (and later?) can be found in the "added_tokens" property of "tokenizer.json".

**Comment by belladoreai** [comment]
Thanks @norlesh !

I went through the differences in the special tokens:
- token 128004 used to be "<|reserved_special_token_2|>" but is now "<|finetune_right_pad_id|>"
- token 128008 used to be "<|reserved_special_token_4|>" but is now "<|eom_id|>"
- token 128010 used to be "<|reserved_special_token_5|>" but is now "<|python_tag|>"
- all other tokens which are currently named "reserved_special_token" have had their ids changed as a result of the 3 changes listed above
- no id shift to other special tokens

I decided to update llama3-tokenizer-js such that it is consistent with llama 3.1 with regards to these changes. That means it's no longer consistent with llama 3. However, that shouldn't matter, because the inconsistencies only affect these reserved special tokens, which should not be in use anyway.

Released version 1.2.0

**Comment by belladoreai** [comment]
Nothing else has come up so I'm closing this for now. Thanks all!
